apiVersion: apps/v1
kind: Deployment
metadata:
  name: witple-backend
  namespace: witple
  labels:
    app: witple-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: witple-backend
  template:
    metadata:
      labels:
        app: witple-backend
    spec:
      containers:
      - name: witple-backend
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY_NAME}:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SECRET_KEY
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ALLOWED_ORIGINS
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: REDIS_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred
