apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: witple
type: Opaque
data:
  DATABASE_URL: "${DATABASE_URL_BASE64}"  # base64 encoded
  REDIS_URL: "${REDIS_URL_BASE64}"  # base64 encoded
